### ISSUE TITLE
Player count not showing for Bungee

### ISSUE THREAD

**Issue by GershonR** [Minecrell/ServerListPlus#114]
I have the servers setup in the bungee config
```
servers:
  hub:
    address: hub.example.com:25683
    restricted: false
    motd: '&1Welcome to our Survival server!'
  pvp:
    address: pvp.example.com:25651
    restricted: false
    motd: '&1Welcome to our pvp server!'
```

I used:
```
- Hub: %online@hub%/250 players online
- PVP: &e%online@games%/500 players online
```

But the it still shows a 0 player count for both
