### ISSUE TITLE
Favicon part is different with wiki in sponge server

### ISSUE THREAD

**Issue by 5igm** [Minecrell/ServerListPlus#126]
ServerListPlus-3.4.6-Universal
spongeforge-1.8.9-1890-4.2.0-BETA-1653
forge-1.8.9-11.15.1.1902-1.8.9-universal

This is my default favicon part in config file:
```
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE

```
If I want to use URLs:https://visage.surgeplay.com/bust/3ee0b3422961496c93be1f87b90ffe25, what should I do?
