### ISSUE TITLE
Favicon Handshake failure

### ISSUE THREAD

**Issue by JamesDemaine** [Minecrell/ServerListPlus#148]
This error comes out when player pings for favicon:
![screen shot 2016-12-05 at 1 53 30 pm](https://cloud.githubusercontent.com/assets/20341206/20884145/4bde33bc-baf2-11e6-83ce-dfdd5ac7d299.png)

I know this was solved in issue #130 .
The difference is that I would like the bust image only available from https://visage.surgeplay.com/bust/64/%_uuid_%
Other websites don't offer a bust image.

Config:
```
--- !Status
Default:
  Favicon:
    Files:
    - icon.png
  Description:
    - |-
      &aCatalyst Empire.
      &l&6The new &aFactions/PvP &6server in town!
    - |-
      &aCatalyst Empire.
      &eWe support &l1.9, 1.10 and 1.11&e!
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &e&l%online%/%max%
Personalized:
  Favicon:
    # Use the head of the player's skin
    URLs:
    - https://visage.surgeplay.com/bust/64/%_uuid_%
  Description:
    - |-
      &aCatalyst Empire. &7|  &eHello, &l%player%!
      &l&6The new &aFactions/PvP &6server in town!
    - |-
      &aCatalyst Empire. &7|  &eHello, &l%player%!
      &eWe support &l1.9, 1.10 and 1.11&e!
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &e&l%online%/%max%

--- !Plugin
Stats: true
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
Samples:
  Multiple: true
  DynamicPlayers: false
Unknown:
  PlayerName: unknown
  PlayerCount: nobody
Favicon:
  Timeout: 15s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE
```
