### ISSUE TITLE
[Request] Toggle section command (Toggle pre-made Event/Maintenence/Sale etc)

### ISSUE THREAD

**Issue by FrozenBeard** [Minecrell/ServerListPlus#231]
I'm requesting a way to enable/disable pre-made messages via a command in-game, creating a new section following the same structure. 

- Toggle messages for your server with **/slp toggle {name}** 
- Enable/Disable **/slp toggle {name} enable/disable** 
- Weight system, If multiple sections are enabled, pick the highest weight
- Timer system, How long the message will be toggled for (In seconds)

Two issues, I need help figuring out with this system:

1.  I use Bungee, how would I be able to send those commands from my XYZ server? The plan would be to automate messages from plugins to run the requested commands. As its being used as bungee plugin for all hosts, we would need a way for each server to trigger the commands to dynamically update.
2. Not sure on the best way to have toggles per host with this method (Below).

Idea of what the section could be formatted like:
```
Toggles:
  Maintenence:
    Default:
      Description:
      - |-
        &e&lFeatureCraft
        &6Survival server!
  Sale:
    Default:
      Weight: 10
      Time: 1200
      Description:
      - |-
        &e&lFeatureCraft
        &cWe have a 50% sale on /store!
      Players:
        Hover:
        - |-
          &dMassive sale on our store items:
          &d* Ranks
          &d* Pets
          &d* Xp Tokens

          &5%random_players@survival,10|, %
  Event:
    Default:
      Description:
      - |-
        &e&lFeatureCraft
        &cGet yourself to /warp event now!
```

**Alternative Method to create toggled messages**

Instead of a new section, an alternative could be to add a variable to all existing messages, the commands would be the same, this would be a different way of knowing what messages are able to be toggled, **ToggleName** & **Weight** would be needed, this way you could use it with the hosts section.

```
Hosts:
  survival.website.com:
    Default:
      Description:
      - |-
        &e&lFeatureCraft
        &6Survival server!
    Sale:
      ToggleName: survivalsale
      Weight: 10
      Description:
      - |-
        &e&lFeatureCraft
        &cWe have a 50% sale on /store!
    Event1:
      ToggleName: event1
      Weight: 5
      Description:
      - |-
        &e&lFeatureCraft
        &cGet yourself to /warp event now!
  creative.website.com:
    Default:
      Description:
      - |-
        &e&lFeatureCraft Creative
        &6Creative server!
    Feature1:
      ToggleName: creativefeature
      Weight: 10
      Description:
      - |-
        &e&lFeatureCraft
        &cNEW FEATURE!
```
