### ISSUE TITLE
Add option to combine different layers of favicons?

### ISSUE THREAD

**Issue by Andre601** [Minecrell/ServerListPlus#240]
Could it be added, to combine multiple favicons into one whole favicon to make it more customizable?

I had something like that in mine:
```yaml
  Favicon:
    Layers:
    - |-
      file:background.png # Loads the image "backgroun"
      url:https://visage.surgeplay.com/head/64/%_uuid_% # Gets the image from the site and adds
      file:layer.png # Loads the image "layer" and adds to the favicon
```

It would load the images from top to bottom, where it adds them one by one before it then gives the final image.
Those most likely have to be prefixed so that it knows exactly from where it needs to get the source.
This would allow a lot of customisation.
