### ISSUE TITLE
Favicon by Host

### ISSUE THREAD

**Issue by hamcoremusic** [Minecrell/ServerListPlus#248]
Don't know is this as already a feature, but I would love to have the same "Hosts" functionalities from the description to work with Favicons!

I have two domains pointing to my server from different "brands" and I would love to have it show the logo for the corresponding brand depending on the URL used.

**Comment by Minecrell** [comment]
Everything that works in `Default` and `Personalized` also works in `Hosts`. Just add it next to `Description` with the correct indentation.

E.g.

```yaml
Hosts:
  pvp.example.com:
    Default:
      Favicon:
        Files:
        - pvp.png
```
Looks funny, doesn't it?
