### ISSUE TITLE
Totalt number of players not displayed.

### ISSUE THREAD

**Issue by alvarlagerlof** [Minecrell/ServerListPlus#252]
I am using bungeecord and the latest version of your plugin. I am using %online% but it only shows then number of players on the hub.

**Comment by alvarlagerlof** [comment]
This started when I set `force_default_server` to true. online@servername works, but that is not what i want. This is what my config looks like

```
connection_throttle_limit: 3
servers:
  hub:
    motd: no not edit here
    restricted: false
    address: localhost:2200
  priv_bons:
    restricted: false
    motd: do not edit here
    address: localhost:33001
  priv_flat:
    restricted: false
    motd: do not edit here
    address: localhost:33002
  priv_hilda:
    restricted: false
    motd: do not edit here
    address: localhost:33003
  priv_ftb:
    restricted: false
    motd: do not edit here
    address: localhost:33004
  mini_parkour:
    restricted: false
    motd: do not edit here
    address: localhost:44001
  mini_dropper:
    restricted: false
    motd: do not edit here
    address: localhost:44002
  mini_hockey:
    restricted: false
    motd: do not edit here
    address: localhost:44003
online_mode: true
log_commands: false
network_compression_threshold: 256
listeners:
- query_port: 25565
  motd: ''
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    blah.ravla.org: lobby
  ping_passthrough: true
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 100
  tab_size: 60
  force_default_server: true
connection_throttle: 4000
groups:
  md_5:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
forge_support: true
stats: ca4e535f-4198-4177-b417-1a0d4fd592e2
disabled_commands:
- disabledcommandhere
timeout: 30000
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
default_server: hub
player_limit: -1
```
