### ISSUE TITLE
[Feature Request]Bungee Per-listeners Status

### ISSUE THREAD

**Issue by alan67160** [Minecrell/ServerListPlus#268]
Like this config, We have 3 listeners and they go to a different server do I hope they have they own status
### bungeecord config.yml:
```
forge_support: false
connection_throttle_limit: -1
online_mode: true
log_commands: true
listeners:
- max_players: 2019
  host: 209.58.***.***:55741
  bind_local_address: true
  ping_passthrough: true
  tab_list: GLOBAL
  priorities:
  - s1
  forced_hosts:
    _minecraft._tcp.ams.play.*****.pro: s1
    _minecraft._tcp.play.*********.xyz: s1
  tab_size: 60
  force_default_server: false
  motd: empty
  query_enabled: false
  query_port: 55739
  proxy_protocol: false
- max_players: 2019
  host: 209.58.***.***:55741
  bind_local_address: true
  ping_passthrough: true
  tab_list: GLOBAL
  priorities:
  - s2
  forced_hosts:
    _minecraft._tcp.ams.play.*****.pro: s2
    _minecraft._tcp.play.*********.xyz: s2
  tab_size: 60
  force_default_server: false
  motd: empty
  query_enabled: false
  query_port: 55740
  proxy_protocol: false
- max_players: 2019
  host: 209.58.***.***:55741
  bind_local_address: true
  ping_passthrough: true
  tab_list: GLOBAL
  priorities:
  - s3
  forced_hosts:
    _minecraft._tcp.ams.play.*****.pro: s3
    _minecraft._tcp.play.*********.xyz: s3
  tab_size: 60
  force_default_server: false
  motd: empty
  query_enabled: false
  query_port: 55741
  proxy_protocol: false
connection_throttle: -1
groups:
  admin1:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
network_compression_threshold: 265
stats: ********-****-****-****-************
inject_commands: false
disabled_commands:
- disabledcommandhere
timeout: 30000
permissions:
  default:
  - bungeecord.command.list
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.send
  - bungeecord.command.find
  - bungeecord.command.reload
servers:
  s1:
    motd: 's1'
    address: 1.34.***.***:20543
    restricted: false
  s2:
    motd: 's2'
    address: 209.58.***.***:51528
    restricted: false
  s3:
    motd: 's3'
    address: 209.58.***.***:25565
    restricted: false
player_limit: -1
```
