### ISSUE TITLE
My server doesnt show my custom code

### ISSUE THREAD

**Issue by TTeetje** [Minecrell/ServerListPlus#281]
So I've recently downloaded the plugin and personalized some code I copied from the internet.
But even after /slp enable and /slp reload the server still shows the default information in the server list. I also dont get any error code in my console.

Here is what it looks like in the list:

![image](https://user-images.githubusercontent.com/63802899/79475742-60c77700-8008-11ea-9ac4-980f3057b1b2.png)

Here are the logs:

16.04 17:34:29 [Server] INFO TTeetje issued server command: /slp reload
16.04 17:34:29 [Server] INFO [ServerListPlus] [Core] Reloading configuration...
16.04 17:34:29 [Server] INFO [ServerListPlus] [Core] Loaded configuration: ServerStatusConf
16.04 17:34:29 [Server] INFO [ServerListPlus] [Core] Loaded configuration: PluginConf

Here is my code: (The description and stuff are in Dutch but I hope that that isnt too big of a problem)

```
#      _____                     __    _     _   _____ _
#     |   __|___ ___ _ _ ___ ___|  |  |_|___| |_|  _  | |_ _ ___
#     |__   | -_|  _| | | -_|  _|  |__| |_ -|  _|   __| | | |_ -|
#     |_____|___|_|  \_/|___|_| |_____|_|___|_| |__|  |_|___|___|
# 
# ServerListPlus v3.4.7 - http://git.io/slp

# More information is available in the Wiki: http://git.io/slp-wiki


# This is the section where you can customize your server status ping!
#  - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
--- !Status
Default:
  Description:
  - |-
    &aServer van de boys.
    &7Welkom op de server van de boys!
  Players:
    Hover:
    - |-
      &aWelkom, &l%player%&a!
      &aMomenteel zijn &e&l%online% &aspelers aan het spelen!
    Slots:
    - '&7» &6&l%online%&c&l/&6&l%max%'
  Favicon:
    Files:
    - Faviocon1.png
Personalized:
  Description:
  - |-
    &3&lDE server van de boys! &6Welkom, &l%player%!
    &6Nu met echte fanfics en naaktfotos van Rieke en Jill!
  Players:
    Hover:
      &aWelkom terug, &l%player%&a!
      &aMomenteel zijn &e&l%online% &aspelers pagga aan het slaan op Rieke of Jill!
    Max:
    - 10..1000
    

    Slots:
    - '&aHallo, %player%! &7» &6&l%online%&c&l/&6&l%max%'
   
  Favicon:
    # Use the head of the player's skin
    #Heads:
    #- '%uuid%'
    Files:
    - favicon1.png
# Stats: Enable/disable sending plugin statistics.
# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# Samples: Toggle using multiple player infos for the player hover message.
#     May prevent the annoying ... and x more ... message for bigger servers
#     DynamicPlayers is special and aligns the number with the number of
#     random players used in placeholders.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
Stats: true
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
Samples:
  Multiple: false
  DynamicPlayers: false
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE
```
