### ISSUE TITLE
[feature-request] SLP Server: more entries for different ports

### ISSUE THREAD

**Issue by RedstoneFuture** [Minecrell/ServerListPlus#322]
I'm not sure about the technical borders behind the idea to realized it, but it would be nice if I can define more than one server to support more server ports with her different MOTD etc.

This feature request / question is (only) for the standalone SLP server. To my knowledge, this feature is not supported, currently.

Config-Example:

```
serverA:
  port: 25565
  Message:
  - |-
    &cDer Server ist &4zurzeit in Wartung&c!
serverB:
  port: 25565
  Message:
  - |-
    &cDer Server ist &4zurzeit in Wartung&c!
[...]
```
