### ISSUE TITLE
Syntax problem

### ISSUE THREAD

**Issue by Fargus5** [Minecrell/ServerListPlus#323]
Hello, I have a problem in the syntax as reported in the config...
Could you be so kind to help me to find the problem?

https://log.mtxserv.com/74yOrlE#L2751

I don't understand what is the problem... because I used this link to make the text:
https://mctools.org/motd-creator?text=%26aArvan+%267%7C++%26eHello%2C+%26l%25player%25%21%0D%0A%269Express+yourself+in+a+rich+experience&center

**Comment by Fargus5** [comment]
Please to find below the configuration that I made

```
# ServerListPlus v3.5.0-SNAPSHOT - https://git.io/slp
# More information is available in the wiki: https://git.io/slp-wiki


# This is the section where you can customize your server status ping!
#  - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
#    - Ban reason: %ban_reason%
#    - Ban operator: %ban_operator%
#    - Ban experiation date: %ban_expiration_date%, %ban_expiration_datetime%
--- !Status
Default:
  Description:
  - |-
                  &e&lWelcome to Arvan&r
       &9Express yourself in a rich experience
  - |-
                  &e&lWelcome to Arvan&r
           &cYou never joined here... why?
  Players:
    Slots:
    - '&7» &6&l%online%&c&l/&6&l%max%'
    Hover:
    - |-
      &aWelcome to &la DevLan Community&a!
      
        - &aArvan: &e%online@world%/999 players online
        - &aNether: &e%online@world_nether%/999 players online
        - &aEnd: &e%online@world_the_end%/999 players online
        - &aMinigames: &e%online@minigames%/999 players online
      
      &aJoin now and play together with &3%random_player% ...
Personalized:
  Description:
  - |-
             &aArvan &7|  &eHello, &l%player%!&r
  &7Now with [&a&lSpecial Items&7], [&a&lMinigames&7], and much more!
  - |-
                  &e&lWelcome to Arvan&r
            &9We are waiting you &6%player%
  - |-
             &aArvan &7|  &eHello, &l%player%!&r
  &7Now with [&a&lSlimefun&7], [&a&lNew Mobs&7], and much more!
  - |-
             &aArvan &7|  &eHello, &l%player%!&r
  &cWe didn't see you from &3%last_online_precise_duration%
  - |-
             &aArvan &7|  &eHello, &l%player%!&r
            &7Now with %random_player%...
  - |-
             &aArvan &7|  &eHello, &l%player%!&r
   &7%random_player% is waiting to play with you...
  - |-
             &aArvan &7|  &eHello, &l%player%!&r
       &9Express yourself in a rich experience
  Players:
    Slots:
    - '&aHey, %player%! &7» &6&l%online%&c&l/&6&l%max%'
    Hover:
    - |-
      &eHello, &l%player%
      
        - &aArvan: &e%online@world%/999 players online
        - &aNether: &e%online@world_nether%/999 players online
        - &aEnd: &e%online@world_the_end%/999 players online
        - &aMinigames: &e%online@minigames%/999 players online
      
      &aJoin now and play together with &3%random_player% ...

# Stats: Enable/disable sending plugin statistics.
# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# Samples: Toggle using multiple player infos for the player hover message.
#     May prevent the annoying ... and x more ... message for bigger servers
#     DynamicPlayers is special and aligns the number with the number of
#     random players used in placeholders.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
Stats: true
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
Samples:
  Multiple: true
  DynamicPlayers: false
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
  BanReason: some reason
  BanOperator: somebody
  BanExpirationDate: never
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE


```
