### ISSUE TITLE
[Cache Question] I need to disable the auto cache creation.

### ISSUE THREAD

**Issue by Taryro55** [Minecrell/ServerListPlus#325]
Hi, I wanted to challenge myself to improve my coding skills, but I soon realized that I'm too new to coding to complete my goal. So here I am, asking because I'm very annoyed, and I can't stop thinking about this issue. 
Basically, each time a user joins, it is added to the file PlayerCache.json, I need to disable this, I have been checking the decompiled code, but can't find a way to disable this. If anyone knows what would be needed to change on the code to achieve this, a comment would be very appreciated!

**Comment by Minecrell** [comment]
You can disable the storage (`PlayerCache.json`) or the player tracking entirely in the configuration file. Just set `PlayerTracking -> Enabled: false` or `Storage -> Enabled: false`:

```yaml
--- !Plugin
# ...
PlayerTracking:
  Enabled: false
  Storage: !JSONStorage
    Enabled: false
    SaveDelay: 5m
# ...
```
