### ISSUE TITLE
Advancedban not working

### ISSUE THREAD

**Issue by JohnB17** [Minecrell/ServerListPlus#342]
I banned my alt with Advancedban, but it still showed the normal motd. Here is my `ServerListPlus.yml`

```
#      _____                     __    _     _   _____ _
#     |   __|___ ___ _ _ ___ ___|  |  |_|___| |_|  _  | |_ _ ___
#     |__   | -_|  _| | | -_|  _|  |__| |_ -|  _|   __| | | |_ -|
#     |_____|___|_|  \_/|___|_| |_____|_|___|_| |__|  |_|___|___|
# 
# ServerListPlus v3.4.8 - http://git.io/slp

# More information is available in the Wiki: http://git.io/slp-wiki


# This is the section where you can customize your server status ping!
#  - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
--- !Status
Default:
  Description:
  - |-
    &a[REDACTED] Minecraft Network.
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
  - |-
    &a[REDACTED] Minecraft Network.
    &eWe have updated our server to &lMinecraft 1.8&e!
  Favicon:
    Files:
    - favicon.png
  Players:
    Hover:
    - |-
      &aWelcome to &l[REDACTED] Minecraft Network&a!
      
        - &aLobby: &e%online@lobby%/20 players online
        - &aMinigames: &e%online@minigames%/20 players online
        - &a[REDACTED] SMP: &e%online@[REDACTED]smp%/20 players online
      
      &aThere is a total of %online%/20  ...
Banned:
  Description:
  - |-
    &a[REDACTED] Minecraft Network.
    Seems you're banned! Goodbye
  - |-
    &a[REDACTED] Minecraft Network.
    Nope. You can't come in.
#  Description:
#  - |-
#    &aA Minecraft Network. &7|  &eHello, &l%player%!
#    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
#  - |-
#    &aA Minecraft Network. &7|  &eHello, &l%player%!
#    &eWe have updated our server to &lMinecraft 1.8&e!
#  Players:
#    Hover:
#    - |-
#      &aWelcome back, &l%player%&a!
#      &aCurrently &e&l%online% &aplayers are playing on our server!

# Stats: Enable/disable sending plugin statistics.
# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# Samples: Toggle using multiple player infos for the player hover message.
#     May prevent the annoying ... and x more ... message for bigger servers
#     DynamicPlayers is special and aligns the number with the number of
#     random players used in placeholders.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
Stats: true
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
Samples:
  Multiple: true
  DynamicPlayers: false
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE
```
