### ISSUE TITLE
Favicon.Folders and Favicon.Files not recognized

### ISSUE THREAD

**Issue by SlimeDog** [Minecrell/ServerListPlus#347]
Based on the instructions at [http://git.io/oMhJlg](http://git.io/oMhJlg) (as I understand them)
with the following configuration:
```
Favicon:
  Folders:
  - ../../    # that is, the server root directory
  Files:
  - server-icon.png
```
yields:
```
[08:11:35] [Server thread/WARN]: [ServerListPlus] [Core] Unknown configuration property: Folders @ FaviconConf
[08:11:35] [Server thread/WARN]: [ServerListPlus] [Core] Unknown configuration property: Files @ FaviconConf
```
