### ISSUE TITLE
Server icon doesnt change

### ISSUE THREAD

**Issue by Espinete1987** [Minecrell/ServerListPlus#349]
Hello, i found this plugin becouse i cant change the picture of my server lobby, i have changed time ago once, and now i simply cant, i have removed all the server-icon.png in 64x64 in the server folder, and it still showing the last one, doesnt matters what i do.

Im using your last version of plugin, and MC 1.15.2

So i came here to ask if im doing something wrong,  or even your plugin cant change the picture of my server, but the enable and disable, and the text, it does.

So here is the config

```yaml
--- !Status
Default:
  Description:
  - |-
    &aA Minecraft Server.
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
  - |-
    &aA Minecraft Server.
    &eWe have updated our server to &lMinecraft 1.8&e!
  Players:
    Hover:
    - |-
      &aWelcome to &lA Minecraft Server&a!
      &aCurrently &e&l%online% &aplayers are playing on our server!
Personalized:
  Description:
  - |-
    &aA Minecraft Culo. &7|  &eHello, &l%player%!
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
  - |-
    &aA Minecraft Network. &7|  &eHello, &l%player%!
    &eWe have updated our server to &lMinecraft 1.8&e!
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &aCurrently &e&l%online% &aplayers are playing on our server!
  Favicon:
    # The file names here should be relative to the plugin folder.
    Files:
    - favicon1.png
    - favicon2.png"
```
    Here is the folder [url=https://ibb.co/8jRbKvJ][img]https://i.ibb.co/HrMCFw0/afsdfsf.jpg[/img][/url]
    
    I also have tried with folder way

```
    Personalized:
  Description:
  - |-
    &aA Minecraft Culote. &7|  &eHello, &l%player%!
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
  - |-
    &aA Minecraft Network. &7|  &eHello, &l%player%!
    &eWe have updated our server to &lMinecraft 1.8&e!
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &aCurrently &e&l%online% &aplayers are playing on our server!
  Favicon:
    # The file names here should be relative to the plugin folder.
    Folders:
    - icons
```

[url=https://ibb.co/JytsDTW][img]https://i.ibb.co/Br3C0JH/favicons2.jpg[/img][/url]

I try to disable, reload, enable and nothing >.<
I have used this page http://www.xiconeditor.com/ and also another
I have tried different picture also.

Lets see if you can help me please, thanks
