### ISSUE TITLE
RGB colors %gradient%

### ISSUE THREAD

**Issue by 6test55566** [Minecrell/ServerListPlus#357]
RGB colors not working 
![image](https://user-images.githubusercontent.com/77003234/121692916-42a4bc00-cad1-11eb-8429-378b1c358959.png)

**Comment by Minecrell** [comment]
> **Note:** ServerListPlus 3.5.0 required (although it works sometimes with the alternative syntax on older versions). Until it's released you can [download the development builds](https://ci.codemc.io/job/Minecrell/job/ServerListPlus/).

**Comment by 6test55566** [comment]
it is on 3.5.0

**Comment by Minecrell** [comment]
Well, do you have the _latest_?

**Comment by 6test55566** [comment]
yep

**Comment by Minecrell** [comment]
Please post the configuration.

**Comment by 6test55566** [comment]
```
#      _____                     __    _     _   _____ _
#     |   __|___ ___ _ _ ___ ___|  |  |_|___| |_|  _  | |_ _ ___
#     |__   | -_|  _| | | -_|  _|  |__| |_ -|  _|   __| | | |_ -|
#     |_____|___|_|  \_/|___|_| |_____|_|___|_| |__|  |_|___|___|
# 
# ServerListPlus v3.4.8 - http://git.io/slp

# More information is available in the Wiki: http://git.io/slp-wiki


# This is the section where you can customize your server status ping!
#  - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
--- !Status
Default:
  Description:
    - |-
            %gradient#45bf55#00abd8%  E  %gradient%&7[1.16+]    
            &9&l↠ &b&lInbeParty &7&l◘ &c&lSurvival &7&l◘ &2&lHungerGames &E&lועוד &9&l↞ 
    - |-
            %gradient#45bf55#00abd8%  E  %gradient%&7[1.16+]    
            &9&l↠ &b&lInbeParty &7&l◘ &c&lSurvival &7&l◘ &2&lHungerGames &E&lועוד &9&l↞ 
  Players:
    Slots:
    - '&7» &6&l%online%&c&l/&6&l%max%'

# Stats: Enable/disable sending plugin statistics.
# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# Samples: Toggle using multiple player infos for the player hover message.
#     May prevent the annoying ... and x more ... message for bigger servers
#     DynamicPlayers is special and aligns the number with the number of
#     random players used in placeholders.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
Stats: true
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: false
    SaveDelay: 5m
Samples:
  Multiple: false
  DynamicPlayers: false
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE
--- 1---!Status Default Description - 2- &d&k|&6&l♦ &9Welcome to Inbar Server &6&l♦&d&k|&r &d&k|&r &4&lInbeParty &7&l◘ &2&lSurvival &7&l◘ &5&lInPlot &7&l+ &E&lMore!&d&k| - |- &aA Minecraft Server. &eWe have updated our server to &lMinecraft 1.8&e! Players Hover - |- &aWelcome to &lA Minecraft Server&a! &aCurrently &e&l%online% &aplayers are playing on our server! Personalized Description - |- &d&k|&6&l♦ &9Welcome to Inbar Server &6&l♦&d&k|&r &d&k|&r &4&lInbeParty &7&l◘ &2&lSurvival &7&l◘ &5&lInPlot &7&l◘ &E&lAnd more soon &d&k| - |- &aA Minecraft Network. &7|  &eHello, &l%player%! &eWe have updated our server to &lMinecraft 1.8&e! Players Hover - |- &d&k|&6&l♦ &9Welcome to Inbar Server &6&l♦&d&k|&r &d&k|&r &4&lInbeParty &7&l◘ &2&lSurvival &7&l◘ &5&lInPlot &7&l◘ &E&lAnd more soon &d&k|'
```
