### ISSUE TITLE
can i use multy line in hover?

### ISSUE THREAD

**Issue by 6test55566** [Minecrell/ServerListPlus#360]
i am trying to make multy hover thing and it's not working

this is the code 
↓ ↓ ↓ ↓ ↓ ↓ 
```
  Players:
    Slots:
    - '&7» &7&l%online%&7/&7&l%max%'
    Hover:
    - 'ברוך הבא %player% ברוך הבא לשרת של:'
    - 'E'
```

and this is what i get
↓ ↓ ↓ ↓ ↓ ↓ ↓ 

![image](https://user-images.githubusercontent.com/77003234/121815904-542cc600-cc81-11eb-8ddc-6cfa1d6f9e4b.png)
