### ISSUE TITLE
Favicon not working.

### ISSUE THREAD

**Issue by FluxxyBoi** [Minecrell/ServerListPlus#405]
# Issue with FAVICONS

Hello there! I want to use my favicon which is named server-icon.png . How do I do that?
I've added a section called Files in which I've added a list [only one] of favicon(s). Here is my config file of SLP:

```yaml
# ServerListPlus v3.5.0 - https://git.io/slp
# More information is available in the wiki: https://git.io/slp-wiki

 # This is the section where you can customize your server status ping!
 # - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - You can use formatting codes (&c, &l etc) and hex RGB color codes (&#rrggbb).
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
#    - Ban reason: %ban_reason%
#    - Ban operator: %ban_operator%
#    - Ban experiation date: %ban_expiration_date%, %ban_expiration_datetime%
--- !Status
Default:
  Description:
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &eJoin now for an &lAmazing &eExperience!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &e%gradient#ffbe00#f4511e%We''re newly released!!%gradient%
  Players:
    Hover:
    - |-
      &aWelcome to &lA Minecraft Server&a!
      &aCurrently &e&l%online%/%max% &aplayers are playing on our server!
Personalized:
  Description:
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &7Now with [&a&lLifesteal&7], [&a&lBedwars&7], and much more!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &eWelcome to the server, &a&l%player%
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &e%gradient#ffbe00#f4511e%Newly Released! Hello %player%!%gradient%
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &aCurrently &e&l%online%/%max% &aplayers are playing on our server!

# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# StripRGBIfOutdated: Strip RGB color codes for outdated clients.
#   - With this enabled you can put an old color code (e.g. &c) before RGB codes/gradients
#     and they will be shown for outdated clients.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
StripRGBIfOutdated: true
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
  BanReason: some reason
  BanOperator: somebody
  BanExpirationDate: never
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE
  Files:
  - server-icon.png
```

For some reason, The favicon doesn't show on minecraft. The favicon is in both, the main directory and plugins folder, I've tried in doing in one but that didn't work. Any help would be appriciated.

**Comment by stephan-gh** [comment]
You need to add the `Favicon:` part within the `!Status` section. Don't add new lines below  `!Plugin`. See e.g. the example in https://github.com/Minecrell/ServerListPlus/wiki/Examples (that one uses Favicon -> Heads instead of Files but the concept is the same)

**Comment by FluxxyBoi** [comment]
My config:

`# ServerListPlus v3.5.0 - https://git.io/slp
# More information is available in the wiki: https://git.io/slp-wiki

# This is the section where you can customize your server status ping!
#  - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - You can use formatting codes (&c, &l etc) and hex RGB color codes (&#rrggbb).
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
#    - Ban reason: %ban_reason%
#    - Ban operator: %ban_operator%
#    - Ban experiation date: %ban_expiration_date%, %ban_expiration_datetime%
--- !Status
Default:
  Description:
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &eJoin now for an &lAmazing &eExperience!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &e%gradient#ffbe00#f4511e%We''re newly released!!%gradient%
  Players:
    Hover:
    - |-
      &aWelcome to &lA Minecraft Server&a!
      &aCurrently &e&l%online%/%max% &aplayers are playing on our server!
  Favicon:
  	Files:
  	- server-icon.png
Personalized:
  Description:
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &7Now with [&a&lLifesteal&7], [&a&lBedwars&7], and much more!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &eWelcome to the server, &a&l%player%
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &e%gradient#ffbe00#f4511e%Newly Released! Hello %player%!%gradient%
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &aCurrently &e&l%online%/%max% &aplayers are playing on our server!
   Favicon:
   	Files:
  	- server-icon.png

# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# StripRGBIfOutdated: Strip RGB color codes for outdated clients.
#   - With this enabled you can put an old color code (e.g. &c) before RGB codes/gradients
#     and they will be shown for outdated clients.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
StripRGBIfOutdated: true
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
  BanReason: some reason
  BanOperator: somebody
  BanExpirationDate: never
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE
  Files:
  - server-icon.png

`



Error:

`[15:10:30 WARN] [ServerListPlus]: [Core] Unable to parse a part of the configuration. Make sure the YAML syntax is valid!
net.minecrell.serverlistplus.core.lib.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 49, column 3:
        Files:
      ^

        at net.minecrell.serverlistplus.core.lib.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:445) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:671) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeNode(Composer.java:205) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeKeyNode(Composer.java:359) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:344) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.getNode(Composer.java:131) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:162) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.Yaml$1.next(Yaml.java:515) ~[?:?]
        at net.minecrell.serverlistplus.core.ConfigurationManager.reload(ConfigurationManager.java:91) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:197) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:146) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:92) ~[?:?]
        at net.minecrell.serverlistplus.bungee.BungeePlugin.onEnable(BungeePlugin.java:93) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
[15:10:30 ERROR] [ServerListPlus]: [Core] Unable to parse the configuration. Make sure the YAML syntax is correct!
net.minecrell.serverlistplus.core.lib.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 49, column 3:
        Files:
      ^

        at net.minecrell.serverlistplus.core.lib.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:445) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:669) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.checkNode(Composer.java:105) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:149) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.Yaml$1.hasNext(Yaml.java:510) ~[?:?]
        at net.minecrell.serverlistplus.core.ConfigurationManager.reload(ConfigurationManager.java:88) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:197) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:146) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:92) ~[?:?]
        at net.minecrell.serverlistplus.bungee.BungeePlugin.onEnable(BungeePlugin.java:93) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
[15:10:30 INFO] [ServerListPlus]: Please fix the error before restarting the server!`

**Comment by stephan-gh** [comment]
Try to read the error message:

> **(Do not use \t(TAB) for indentation)**

**Comment by FluxxyBoi** [comment]
I figured it out right I was posting this, I fixed it but now I'm getting this:

```net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 52, column 3:
      Description:
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 67, column 4:
       Favicon:
       ^

        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:656) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeMappingNode(Composer.java:330) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.getNode(Composer.java:131) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:162) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.Yaml$1.next(Yaml.java:515) ~[?:?]
        at net.minecrell.serverlistplus.core.ConfigurationManager.reload(ConfigurationManager.java:91) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:197) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:146) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:92) ~[?:?]
        at net.minecrell.serverlistplus.bungee.BungeePlugin.onEnable(BungeePlugin.java:93) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
[15:17:16 ERROR] [ServerListPlus]: [Core] Unable to parse the configuration. Make sure the YAML syntax is correct!
net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 32, column 1:
    Default:
    ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 67, column 4:
       Favicon:
       ^

        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:656) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.composer.Composer.checkNode(Composer.java:105) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:149) ~[?:?]
        at net.minecrell.serverlistplus.core.lib.snakeyaml.Yaml$1.hasNext(Yaml.java:510) ~[?:?]
        at net.minecrell.serverlistplus.core.ConfigurationManager.reload(ConfigurationManager.java:88) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.reload(ServerListPlusCore.java:197) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:146) ~[?:?]
        at net.minecrell.serverlistplus.core.ServerListPlusCore.<init>(ServerListPlusCore.java:92) ~[?:?]
        at net.minecrell.serverlistplus.bungee.BungeePlugin.onEnable(BungeePlugin.java:93) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
[15:17:16 INFO] [ServerListPlus]: Please fix the error before restarting the server!```

**Comment by stephan-gh** [comment]
You have some new syntax error now. You didn't post your configuration so it's hard to tell what exactly.

**Comment by FluxxyBoi** [comment]
I'll post it here:


```# ServerListPlus v3.5.0 - https://git.io/slp
# More information is available in the wiki: https://git.io/slp-wiki

# This is the section where you can customize your server status ping!
#  - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - You can use formatting codes (&c, &l etc) and hex RGB color codes (&#rrggbb).
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
#    - Ban reason: %ban_reason%
#    - Ban operator: %ban_operator%
#    - Ban experiation date: %ban_expiration_date%, %ban_expiration_datetime%
--- !Status
Default:
  Description:
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &7Now with [&a&lPvP&7], [&a&lMinigames&7], and much more!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &eJoin now for an &lAmazing &eExperience!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &e%gradient#ffbe00#f4511e%We''re newly released!!%gradient%
  Players:
    Hover:
    - |-
      &aWelcome to &lA Minecraft Server&a!
      &aCurrently &e&l%online%/%max% &aplayers are playing on our server!
  Favicon:
    Files:
    - server-icon.png
Personalized:
  Description:
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &7Now with [&a&lLifesteal&7], [&a&lBedwars&7], and much more!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &eWelcome to the server, &a&l%player%
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &e%gradient#ffbe00#f4511e%Newly Released! Hello %player%!%gradient%
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &aCurrently &e&l%online%/%max% &aplayers are playing on our server!
   Favicon:
    Files:
    - server-icon.png

# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# StripRGBIfOutdated: Strip RGB color codes for outdated clients.
#   - With this enabled you can put an old color code (e.g. &c) before RGB codes/gradients
#     and they will be shown for outdated clients.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
StripRGBIfOutdated: true
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
  BanReason: some reason
  BanOperator: somebody
  BanExpirationDate: never
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE
  Files:
  - server-icon.png

```

**Comment by stephan-gh** [comment]
If you read the error closely it tells you exactly where to look for the mistake:

```
 in 'reader', line 52, column 3:
      Description:
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 67, column 4:
       Favicon:
       ^
```

So you look around line 67 which is the `Favicon:` line inside:

```yaml
Personalized:
  Description:
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &7Now with [&a&lLifesteal&7], [&a&lBedwars&7], and much more!
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &eWelcome to the server, &a&l%player%
  - |-
    &4&k--&c&k--&4&k--&c&k--&5&k--&d&k--&5&k--&d&k--&5&k--&6&lGemsMC&3&k--&1&k--&3&k--&1&k--&3&k--&a&k--&2&k--&a&k--&2&k--
    &e%gradient#ffbe00#f4511e%Newly Released! Hello %player%!%gradient%
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &aCurrently &e&l%online%/%max% &aplayers are playing on our server!
   Favicon:  # <----------- HERE
    Files:
    - server-icon.png
```

And if you look closely it looks a bit odd, compared to what you have below `Default`. Compare them closely:

```yaml
Default:
  Favicon:
    Files:
    - server-icon.png
Personalized:
   Favicon:   # <-------- Broken line
    Files:
    - server-icon.png
```

Do you see it?

As a side note, there is no need to duplicate the `Favicon` part into both `Default` and `Personalized` if it's exactly the same. Only add lines to `Personalized` if you want to make it specific to `%player%` (e.g. an individual favicon for each player).
