### ISSUE TITLE
Incompatible version with 1.20.4 (likely ProtocolLib issue, Paper is not affected)

### ISSUE THREAD

**Issue by SlimeDog** [Minecrell/ServerListPlus#406]
Spigot 1.20.4-3966
ServerListPlus 3.5.1-b537

Vanilla MC client 1.20.4

Client cannot connect to remove server.
Client log states: Can't ping <remote server FDQN elided>
Client hover shows "Incompatible version"

**Comment by SlimeDog** [comment]
ServerListPlus.yml, comments elided
```
--- !Status
Default:
  Description:
  - |-
    &f &l{server_name}&r &f▪ {server_variant} {server_version_full}&r &f▪ private network&r
    &r &6⊳&r&aCityWorld &6⊳&r&aExtraHard &6⊳&r&aGoT &6⊳&r&aLuckyBlock &6⊳&r&aSkyBlock &6⊳&r&aWinterland&r
  Players:
    Hover:
    - |-
      &aWoof! Woof!
      &aWho let the dogs in?
  Favicon:
    Folders:
    - ../../
Personalized:
  Description:
  - |-
    &f &l{server_name}&r &f▪ {server_variant} {server_version_full}&r &f▪ private network&r
    &r &6⊳&r&aCityWorld &6⊳&r&aExtraHard &6⊳&r&aGoT &6⊳&r&aLuckyBlock &6⊳&r&aSkyBlock &6⊳&r&aWinterland&r
  Players:
    Hover:
    - |-
      &aWoof! Woof!
      &aWho let the dogs in?

--- !Plugin
PlayerTracking:
  Enabled: false
  Storage: !JSONStorage
    Enabled: false
    SaveDelay: 5m
StripRGBIfOutdated: true
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
  BanReason: some reason
  BanOperator: somebody
  BanExpirationDate: never
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE

--- !Bukkit
ProtocolLib: ENABLE
```
