### ISSUE TITLE
Disabling the slots per host if default uses the feature

### ISSUE THREAD

**Issue by fish-eater** [Minecrell/ServerListPlus#432]
Lets say I have this setup:

```yaml
Hosts:
  server1.gfsfeijrg.com:
    Default:
      Description:
      - |-
        &aThis is the PvP Server!
      Players:
       Max:
       - 20
       # i wish here there could be a Slots: disable option

   server2.gfsfeijrg.com:
    Default:
      Description:
      - |-
        &aThis is the Games Server!
      Players:
       Max:
       - 40

Default:
  Description:
  - |-
    &#ff0c0cCan't connect to server
  Players:
    Slots:
    - ''
```

in this setup, the per-hosts overwrite the default, which is when there's no proper velocity server to go to. works well, but i don't want the crossed out ping for my up servers, just the default down ones.

the issue is there doesn't seem to be an option to disable the Slots option, just overwriting it from the default.
