### ISSUE TITLE
Virtual hosts doesn't seem to support SRV

### ISSUE THREAD

**Issue by frdmn** [Minecrell/ServerListPlus#52]
I'm using the following configuration part for my virtual hosts:

```yaml
Hosts:
  frd.mn:
    Default:
      Description:
      - |-
        &a&lYEAHWHAT?!&r&6 Minecraft server.
        &6Still using &4&lfrd.mn&6, eh?
    Personalized:
      Description:
      - |-
        &6Welcome back to &a&lYEAHWHAT?!&r&6, &c%player%&6!
        &6Still using &4&lfrd.mn&6, eh?
```

However, if I connect to "`frd.mn`", which is using an SRV to "`obi-wan.yeahwh.at:25575`":

    $ dig srv _minecraft._tcp.frd.mn +short
    1 1 25575 obi-wan.yeahwh.at.

... It still show's me the default Description, and not the "per-host" one i've set for "frd.mn"

Anything I done wrong?

Thanks in advance

**Comment by Minecrell** [comment]
Are you using the Bukkit or the BungeeCord version? If you're on Bukkit, make sure to install ProtocolLib. Otherwise it should work, although I'm going to verify this for the newer versions.

**Comment by frdmn** [comment]
@Minecrell I'm using the latest Spigot/Bukkit version (ServerListPlusUniversal_3.3.2.jar). I also made sure the latest verison of ProtocolLib is installed (ProtocolLib_3.6.3b75.jar from Jenkins).

**Comment by frdmn** [comment]
Is this resolved now?

**Comment by Minecrell** [comment]
It should, I've tested it before releasing the new version (3.4). If it is still not working, write here again then I can take a look again.

**Comment by frdmn** [comment]
Thanks, i'll report back as soon as i tried said version :+1:

**Comment by frdmn** [comment]
@Minecrell Just tried the latest release from GitHub releases. Still no luck:

My server connections:

![bildschirmfoto 2015-06-29 um 13 52 09](https://cloud.githubusercontent.com/assets/944459/8407362/2e05831a-1e66-11e5-9784-aa61c5f63311.png)

![bildschirmfoto 2015-06-29 um 13 52 05](https://cloud.githubusercontent.com/assets/944459/8407361/2e051268-1e66-11e5-9d1f-af8c8530ef04.png)

---

![bildschirmfoto 2015-06-29 um 13 52 12](https://cloud.githubusercontent.com/assets/944459/8407374/3e8f7330-1e66-11e5-9549-619e3c52a68e.png)

**Comment by Minecrell** [comment]
I don't know exactly but let me guess: SRV records get resolved on the client. Then, it simply connects with the IP that's in there. It is probably sending the resolved SRV address to the server, so there is no way to get the original SRV hostname used in the Minecraft client. For this SRV record, it is simply always sending `obi-wan.yeahwh.at:25575` to the server instead of `frd.mn` as you would expect.

You can define a special hostname in the SRV record to be still able to detect this SRV record.

**Note:** Not completely sure about this, would need to check first to make sure this is the reason.

**Comment by frdmn** [comment]
@Minecrell You are right, when I try this in the configuration:

```yaml
Hosts:
  obi-wan.yeahwh.at:
    Default:
      Description:
      - |-
        &a&lYEAHWHAT?!&r&6 Minecraft server.
        &6Still using &4&lfrd.mn&6, eh?
    Personalized:
      Description:
      - |-
        &6Welcome back to &a&lYEAHWHAT?!&r&6, &c%player%&6!
        &6Still using &4&lfrd.mn&6, eh?
```

... I see said description, but I am not sure if that's the "purposed" behaviour.

ideas?
