### ISSUE TITLE
Virtual host's don't working

### ISSUE THREAD

**Issue by kukubaczek** [Minecrell/ServerListPlus#62]
Config:
```
Hosts:
  dziarnos.fireland.pl:
    Default:
      Description:
      - |-
        &atest
```

Effect:
dziarnos.fireland.pl:25582
